DOCB ::=    '\BEGIN'
DOCE ::=    '\END'
TITLEB ::=  '\TITLE['
BRACKETE ::=  ']'
HEADING ::=  '#'
PARB ::=  '\PARB'
PARE ::=  '\PARE'
BOLD ::=  '*'
LISTITEM ::=   '+'
NEWLINE ::=  '\\'
LINKB ::=  '['
ADDRESSB ::=  '('
ADDRESSE ::=  ')'
IMAGEB ::=  '!['
DEFB ::=  '\DEF['
EQSIGN ::=  '='
USEB ::=  '\USE['
REQTEXT ::=  Any plain text
TEXT ::=  Any plain text | empty